
name: CI Tests

on:
  push:
    branches:
      - main
      - release/current
      - release/hotfix
  pull_request:
    branches:
      - main
      - release/current
      - release/hotfix

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: 16.x
      - name: Install Linux deps
        run: sudo apt install xvfb -y
      - name: Install all
        run: npm run install:all
      - name: Build everything
        run: npm run build:all
      - name: Run Unit tests
        run: npm run test:unit
      - name: Run E2E tests
        run: xvfb-run -a npm run test:e2e

